// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iok200.okmax.admin.model.proto

package iok200_okmax_admin_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	iok200_blada_pb "github.com/iok200/blada/pb/iok200_blada_pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 权限类型
type AuthType int32

const (
	// 菜单
	AuthType_Menu AuthType = 0
	// 功能
	AuthType_Function AuthType = 1
)

var AuthType_name = map[int32]string{
	0: "Menu",
	1: "Function",
}

var AuthType_value = map[string]int32{
	"Menu":     0,
	"Function": 1,
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}

func (AuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c34b4f1b99688a56, []int{0}
}

// 用户
type User struct {
	Basic *iok200_blada_pb.Model `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	// 账号
	LoginName string `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	// 密码
	LoginPass string `protobuf:"bytes,3,opt,name=loginPass,proto3" json:"loginPass,omitempty"`
	// 用户名
	UserName string `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	// 是否可用
	Enable               bool     `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c34b4f1b99688a56, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetBasic() *iok200_blada_pb.Model {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *User) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *User) GetLoginPass() string {
	if m != nil {
		return m.LoginPass
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 角色
type Role struct {
	Basic *iok200_blada_pb.Model `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	// 角色名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 角色描述
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	// 是否可用
	Enable               bool     `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_c34b4f1b99688a56, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetBasic() *iok200_blada_pb.Model {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Role) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 权限
type Auth struct {
	Basic *iok200_blada_pb.Model `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	// 权限名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 权限描述
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	// 权限类型
	Type AuthType `protobuf:"varint,4,opt,name=type,proto3,enum=iok200.okmax.admin.AuthType" json:"type,omitempty"`
	// 图标
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	// 路径
	Path string `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	// 上级权限ID
	Pid string `protobuf:"bytes,7,opt,name=pid,proto3" json:"pid,omitempty"`
	// 是否可用
	Enable               bool     `protobuf:"varint,8,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c34b4f1b99688a56, []int{2}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetBasic() *iok200_blada_pb.Model {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Auth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Auth) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Auth) GetType() AuthType {
	if m != nil {
		return m.Type
	}
	return AuthType_Menu
}

func (m *Auth) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Auth) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Auth) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Auth) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func init() {
	proto.RegisterEnum("iok200.okmax.admin.AuthType", AuthType_name, AuthType_value)
	proto.RegisterType((*User)(nil), "iok200.okmax.admin.User")
	proto.RegisterType((*Role)(nil), "iok200.okmax.admin.Role")
	proto.RegisterType((*Auth)(nil), "iok200.okmax.admin.Auth")
}

func init() {
	proto.RegisterFile("iok200.okmax.admin.model.proto", fileDescriptor_c34b4f1b99688a56)
}

var fileDescriptor_c34b4f1b99688a56 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x76, 0x5b, 0xd3, 0x67, 0x91, 0xb2, 0x88, 0x84, 0x52, 0xa4, 0xf4, 0x54, 0x0a, 0x4d,
	0x4b, 0xbd, 0x89, 0x17, 0x3d, 0x78, 0xab, 0x48, 0xd0, 0x8b, 0x97, 0xb2, 0x49, 0xd7, 0x76, 0x69,
	0xb2, 0x6f, 0xc9, 0x07, 0xd8, 0xbf, 0xe3, 0x0f, 0xf3, 0xb7, 0xc8, 0xbe, 0xc4, 0x36, 0xa2, 0x17,
	0x0f, 0xde, 0x66, 0x67, 0x66, 0xdf, 0xcc, 0x4b, 0x16, 0x2e, 0x15, 0x6e, 0xe7, 0xb3, 0x99, 0x8f,
	0xdb, 0x44, 0xbc, 0xf9, 0x62, 0x95, 0x28, 0xed, 0x27, 0xb8, 0x92, 0xb1, 0x6f, 0x52, 0xcc, 0x91,
	0xf3, 0x9f, 0x7a, 0xaf, 0x13, 0x61, 0x92, 0xa0, 0x2e, 0x1d, 0xc3, 0x77, 0x07, 0xd8, 0x73, 0x26,
	0x53, 0x3e, 0x86, 0x66, 0x28, 0x32, 0x15, 0x79, 0xce, 0xc0, 0x19, 0x9d, 0xce, 0xcf, 0xfd, 0xea,
	0x6a, 0xe5, 0x5e, 0xd8, 0xa9, 0x41, 0x69, 0xe1, 0x7d, 0x68, 0xc7, 0xb8, 0x56, 0xfa, 0x41, 0x24,
	0xd2, 0x3b, 0x1e, 0x38, 0xa3, 0x76, 0x70, 0x20, 0xf6, 0xea, 0xa3, 0xc8, 0x32, 0xaf, 0x51, 0x53,
	0x2d, 0xc1, 0x7b, 0xe0, 0x16, 0x99, 0x4c, 0xe9, 0x2a, 0x23, 0x71, 0x7f, 0xe6, 0x17, 0xd0, 0x92,
	0x5a, 0x84, 0xb1, 0xf4, 0x9a, 0x03, 0x67, 0xe4, 0x06, 0xd5, 0x69, 0x98, 0x02, 0x0b, 0x30, 0x96,
	0x7f, 0xea, 0xc8, 0x81, 0xe9, 0x43, 0x3d, 0xc2, 0x96, 0x53, 0xfa, 0x15, 0xab, 0x52, 0x84, 0x6b,
	0x99, 0xec, 0x5b, 0xe6, 0x87, 0x03, 0xec, 0xb6, 0xc8, 0x37, 0xff, 0x12, 0x3a, 0x03, 0x96, 0xef,
	0x4c, 0x19, 0x79, 0x36, 0xef, 0xfb, 0xbf, 0xfc, 0x46, 0x9b, 0xfd, 0xb4, 0x33, 0x32, 0x20, 0x27,
	0x4d, 0x89, 0x50, 0xd3, 0x87, 0xb1, 0x53, 0x22, 0xd4, 0x96, 0x33, 0x22, 0xdf, 0x78, 0xad, 0x92,
	0xb3, 0x98, 0x77, 0xa1, 0x61, 0xd4, 0xca, 0x3b, 0x21, 0xca, 0xc2, 0xda, 0x82, 0x6e, 0x7d, 0xc1,
	0xf1, 0x10, 0xdc, 0xaf, 0x0c, 0xee, 0x02, 0x5b, 0x48, 0x5d, 0x74, 0x8f, 0x78, 0x07, 0xdc, 0xfb,
	0x42, 0x47, 0xb9, 0x42, 0xdd, 0x75, 0xee, 0x6e, 0x5e, 0xae, 0xd7, 0x2a, 0xdf, 0x14, 0xa1, 0xdd,
	0x76, 0x5a, 0xb6, 0x9c, 0x52, 0xcb, 0x09, 0xb5, 0x9c, 0x08, 0xa3, 0xa6, 0x26, 0xac, 0x94, 0x25,
	0x29, 0x4b, 0x52, 0x96, 0x26, 0x0c, 0x5b, 0xf4, 0xc4, 0xae, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x85, 0x16, 0x48, 0x83, 0xa6, 0x02, 0x00, 0x00,
}
