// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iok200.okmax.admin.auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	pb "github.com/iok200/blada/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthCreateRequest struct {
	// 权限信息
	Auth *Auth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	// 权限ID
	AuthIds              []string `protobuf:"bytes,2,rep,name=authIds,proto3" json:"authIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthCreateRequest) Reset()         { *m = AuthCreateRequest{} }
func (m *AuthCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthCreateRequest) ProtoMessage()    {}
func (*AuthCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5591d91dcb0543c4, []int{0}
}

func (m *AuthCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthCreateRequest.Unmarshal(m, b)
}
func (m *AuthCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthCreateRequest.Marshal(b, m, deterministic)
}
func (m *AuthCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthCreateRequest.Merge(m, src)
}
func (m *AuthCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthCreateRequest.Size(m)
}
func (m *AuthCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthCreateRequest proto.InternalMessageInfo

func (m *AuthCreateRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *AuthCreateRequest) GetAuthIds() []string {
	if m != nil {
		return m.AuthIds
	}
	return nil
}

type AuthUpdateRequest struct {
	// 权限信息
	Auth                 *Auth    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUpdateRequest) Reset()         { *m = AuthUpdateRequest{} }
func (m *AuthUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthUpdateRequest) ProtoMessage()    {}
func (*AuthUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5591d91dcb0543c4, []int{1}
}

func (m *AuthUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUpdateRequest.Unmarshal(m, b)
}
func (m *AuthUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AuthUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUpdateRequest.Merge(m, src)
}
func (m *AuthUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthUpdateRequest.Size(m)
}
func (m *AuthUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUpdateRequest proto.InternalMessageInfo

func (m *AuthUpdateRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type AuthQueryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthQueryRequest) Reset()         { *m = AuthQueryRequest{} }
func (m *AuthQueryRequest) String() string { return proto.CompactTextString(m) }
func (*AuthQueryRequest) ProtoMessage()    {}
func (*AuthQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5591d91dcb0543c4, []int{2}
}

func (m *AuthQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthQueryRequest.Unmarshal(m, b)
}
func (m *AuthQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthQueryRequest.Marshal(b, m, deterministic)
}
func (m *AuthQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthQueryRequest.Merge(m, src)
}
func (m *AuthQueryRequest) XXX_Size() int {
	return xxx_messageInfo_AuthQueryRequest.Size(m)
}
func (m *AuthQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthQueryRequest proto.InternalMessageInfo

type AuthQueryResult struct {
	State *pb.ResultState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// 权限列表
	Auths                []*Auth  `protobuf:"bytes,2,rep,name=auths,proto3" json:"auths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthQueryResult) Reset()         { *m = AuthQueryResult{} }
func (m *AuthQueryResult) String() string { return proto.CompactTextString(m) }
func (*AuthQueryResult) ProtoMessage()    {}
func (*AuthQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5591d91dcb0543c4, []int{3}
}

func (m *AuthQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthQueryResult.Unmarshal(m, b)
}
func (m *AuthQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthQueryResult.Marshal(b, m, deterministic)
}
func (m *AuthQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthQueryResult.Merge(m, src)
}
func (m *AuthQueryResult) XXX_Size() int {
	return xxx_messageInfo_AuthQueryResult.Size(m)
}
func (m *AuthQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthQueryResult proto.InternalMessageInfo

func (m *AuthQueryResult) GetState() *pb.ResultState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AuthQueryResult) GetAuths() []*Auth {
	if m != nil {
		return m.Auths
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthCreateRequest)(nil), "iok200.okmax.admin.AuthCreateRequest")
	proto.RegisterType((*AuthUpdateRequest)(nil), "iok200.okmax.admin.AuthUpdateRequest")
	proto.RegisterType((*AuthQueryRequest)(nil), "iok200.okmax.admin.AuthQueryRequest")
	proto.RegisterType((*AuthQueryResult)(nil), "iok200.okmax.admin.AuthQueryResult")
}

func init() {
	proto.RegisterFile("iok200.okmax.admin.auth.proto", fileDescriptor_5591d91dcb0543c4)
}

var fileDescriptor_5591d91dcb0543c4 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x81, 0xff, 0x07, 0xe3, 0xc5, 0x44, 0x9d, 0x55, 0x6d, 0xa2, 0x21, 0x23, 0x1a, 0x16,
	0x32, 0x10, 0x7c, 0x02, 0x50, 0x17, 0x2c, 0x5c, 0x58, 0x74, 0xa3, 0xab, 0x81, 0xb9, 0x91, 0x86,
	0x96, 0xa9, 0x9d, 0x19, 0x23, 0x6f, 0xe8, 0x63, 0x99, 0xe9, 0x94, 0x04, 0x94, 0x82, 0x71, 0xd5,
	0xdc, 0xde, 0x73, 0xbe, 0x7b, 0x72, 0x5a, 0x38, 0x0d, 0xe5, 0xac, 0xd7, 0xed, 0x32, 0x39, 0x8b,
	0xf9, 0x07, 0xe3, 0x22, 0x0e, 0xe7, 0x8c, 0x1b, 0x3d, 0x65, 0x49, 0x2a, 0xb5, 0x24, 0xe4, 0xe7,
	0xda, 0x3f, 0x98, 0xc8, 0x38, 0x96, 0x73, 0xa7, 0xf0, 0xcf, 0x36, 0x00, 0x62, 0x29, 0x30, 0x72,
	0x7b, 0xfa, 0x02, 0xc7, 0x7d, 0xa3, 0xa7, 0x37, 0x29, 0x72, 0x8d, 0x01, 0xbe, 0x19, 0x54, 0x9a,
	0x5c, 0xc1, 0x7f, 0x7b, 0xc4, 0x2b, 0x37, 0xca, 0xad, 0x7a, 0xcf, 0x63, 0x1b, 0x18, 0xd6, 0x14,
	0x64, 0x2a, 0xe2, 0xc1, 0x9e, 0x7d, 0x0e, 0x85, 0xf2, 0x2a, 0x8d, 0x7f, 0xad, 0xfd, 0x60, 0x39,
	0xd2, 0xbe, 0x83, 0x3f, 0x25, 0xe2, 0xaf, 0x70, 0x4a, 0xe0, 0xc8, 0x4e, 0x0f, 0x06, 0xd3, 0x45,
	0x4e, 0xa0, 0x0a, 0x0e, 0x57, 0xde, 0x29, 0x13, 0x69, 0xd2, 0x85, 0xaa, 0xd2, 0x5c, 0x63, 0x4e,
	0xf5, 0x97, 0xd4, 0xbc, 0x0b, 0xa7, 0x1a, 0x59, 0x45, 0xe0, 0x84, 0x84, 0x41, 0xd5, 0x1e, 0x70,
	0x99, 0xb7, 0xe5, 0x70, 0xb2, 0xde, 0x67, 0x05, 0xea, 0x76, 0x1e, 0x61, 0xfa, 0x1e, 0x4e, 0x90,
	0xdc, 0x43, 0xcd, 0x95, 0x46, 0x2e, 0x8a, 0xac, 0x6b, 0xa5, 0xfa, 0x5b, 0x32, 0xd1, 0x92, 0xc5,
	0xb9, 0x9a, 0x8a, 0x71, 0x6b, 0x35, 0xee, 0xc0, 0xdd, 0x01, 0xdc, 0x62, 0x84, 0x1a, 0x07, 0x8b,
	0xa1, 0x20, 0x27, 0xdf, 0xb4, 0x43, 0xa1, 0x7e, 0x87, 0x79, 0x84, 0x6a, 0xd6, 0x32, 0x69, 0x16,
	0x85, 0x5a, 0xfd, 0x30, 0xfe, 0xf9, 0x0e, 0x95, 0x45, 0xd3, 0xd2, 0xe0, 0xf2, 0xb9, 0xf9, 0x1a,
	0xea, 0xa9, 0x19, 0xdb, 0xa3, 0x1d, 0x67, 0xe9, 0x64, 0x96, 0x76, 0x66, 0x69, 0xf3, 0x24, 0xec,
	0x24, 0xe3, 0x71, 0x2d, 0xfb, 0x45, 0xaf, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0x6c, 0x0e,
	0xf6, 0x05, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// 创建
	Create(ctx context.Context, in *AuthCreateRequest, opts ...grpc.CallOption) (*pb.ResultState, error)
	// 修改
	Update(ctx context.Context, in *AuthUpdateRequest, opts ...grpc.CallOption) (*pb.ResultState, error)
	// ID删除
	DeleteById(ctx context.Context, in *pb.IdsRequest, opts ...grpc.CallOption) (*pb.ResultState, error)
	// 查询
	Query(ctx context.Context, in *AuthQueryRequest, opts ...grpc.CallOption) (*AuthQueryResult, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Create(ctx context.Context, in *AuthCreateRequest, opts ...grpc.CallOption) (*pb.ResultState, error) {
	out := new(pb.ResultState)
	err := c.cc.Invoke(ctx, "/iok200.okmax.admin.AuthService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Update(ctx context.Context, in *AuthUpdateRequest, opts ...grpc.CallOption) (*pb.ResultState, error) {
	out := new(pb.ResultState)
	err := c.cc.Invoke(ctx, "/iok200.okmax.admin.AuthService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteById(ctx context.Context, in *pb.IdsRequest, opts ...grpc.CallOption) (*pb.ResultState, error) {
	out := new(pb.ResultState)
	err := c.cc.Invoke(ctx, "/iok200.okmax.admin.AuthService/DeleteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Query(ctx context.Context, in *AuthQueryRequest, opts ...grpc.CallOption) (*AuthQueryResult, error) {
	out := new(AuthQueryResult)
	err := c.cc.Invoke(ctx, "/iok200.okmax.admin.AuthService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// 创建
	Create(context.Context, *AuthCreateRequest) (*pb.ResultState, error)
	// 修改
	Update(context.Context, *AuthUpdateRequest) (*pb.ResultState, error)
	// ID删除
	DeleteById(context.Context, *pb.IdsRequest) (*pb.ResultState, error)
	// 查询
	Query(context.Context, *AuthQueryRequest) (*AuthQueryResult, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Create(ctx context.Context, req *AuthCreateRequest) (*pb.ResultState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAuthServiceServer) Update(ctx context.Context, req *AuthUpdateRequest) (*pb.ResultState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAuthServiceServer) DeleteById(ctx context.Context, req *pb.IdsRequest) (*pb.ResultState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteById not implemented")
}
func (*UnimplementedAuthServiceServer) Query(ctx context.Context, req *AuthQueryRequest) (*AuthQueryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iok200.okmax.admin.AuthService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Create(ctx, req.(*AuthCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iok200.okmax.admin.AuthService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Update(ctx, req.(*AuthUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.IdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iok200.okmax.admin.AuthService/DeleteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteById(ctx, req.(*pb.IdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iok200.okmax.admin.AuthService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Query(ctx, req.(*AuthQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iok200.okmax.admin.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AuthService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AuthService_Update_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _AuthService_DeleteById_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AuthService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iok200.okmax.admin.auth.proto",
}
